name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install ArrayFire
      run: |
        wget https://arrayfire.s3.amazonaws.com/3.6.4/ArrayFire-v3.6.4_Linux_x86_64.sh
        sh ArrayFire-v3.6.4_Linux_x86_64.sh --prefix=/usr --exclude-subdir --skip-license
    - name: Run cmake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: Run make
      run: make
      working-directory: build
