name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install ArrayFire
      run: |
        sudo apt-get update
        sudo apt-get install -y libarrayfire-unified-dev
    - name: Run cmake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: Run make
      run: make
